config/routes.rb
Rails.application.routes.draw do
  root'pages#home'
  get 'about' , to:'pages#about'
  resources :posts
  get 'signup' , to:'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum: 100} 
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
    before_save{ self.email = email.downcase}
    has_many :posts
    validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }


has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def   
        home
    end
    def 
        about
     end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :set_post, only: [:show, :edit, :destroy, :update]

    def show
    end

    def index
        @posts =  Post.paginate(page: params[:page], per_page: 4)
    end

    def new
        @post = Post.new
    end

    def edit 

    end

    def create
        @post = Post.new(post_params)
        @post.user = User.first
        if @post.save
            flash[:notice] = "Post Was Successfully Saved"
        redirect_to @post
        else
            render 'new'
        end
    end

    def update
       if @post.update(post_params)
            flash[:notice] = "Edit Successful"
        redirect_to @post
       else
        render 'edit'
       end

    end

    def destroy
        @post.destroy
        redirect_to posts_path

    end

private

def set_post
    @post = Post.find(params[:id])
end

def post_params
    params.require(:post).permit(:title, :description)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @posts = @user.posts
      end

      def index
        @users = User.all
      end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
          redirect_to posts_path
        else
          render 'new'
        end
      end

      def edit
        @user = User.find(params[:id])
      end
    
      def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          flash[:notice] = "Your account information was successfully updated"
          redirect_to @user
        else
          render 'edit'
        end
      end
    
      private
      def user_params
        params.require(:user).permit(:username, :email, :password)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg|%>
    <%= msg%>
    <%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "20 After Four", root_path, class:"navbar-brand", id:"logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">

      <%= link_to "Posts", posts_path, class:"nav-link" %>   
         </li>
      <li class="nav-item">
      <%= link_to "About", about_path, class:"nav-link" %> 
      </li>
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
          
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>

          
        </div>
        
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SusBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
     <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is the about</h1>

<%= link_to 'Go to posts ',posts_path%> |
<%= link_to 'Go to Home ',root_path%> 

app/views/pages/home.html.erb
<div class= "container" id="home-container">
<div class="jumbotron text-center text-white" >
  <h1 class="display-4">Hello & Welcome</h1>
  <p class="lead">The Adventure Is Waiting For You To Sign Up</p>
  <hr class="my-4">
  <p>What Are You Waiting For?</p>
  <p class="lead">
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
  </p>
</div>

</div>

app/views/posts/_forms.html.erb
<div class  = "container">
<% if @post.errors.any? %>
<h2>The following error or errors occured</h2>
<ul>
<% @post.errors.full_messages.each do |msg|%>
   <li> <%= msg %> </li>
  <% end %>
</ul>
<% end %>
<div class= "row justify-content-center">
<div class = "col-10">
<%= form_with( model: @post, class:"shadow-p-3 mb-5 bg-info rounded", local: true) do |f| %>
  <div class= "form-group row">
<%= f.label :title, class: "col-2 col-form-label"%> 
<div class = "col-10">
<%=  f.text_field :title, class: "form-control"%>
</div>
</div>

<div class= "form-group row">
<%= f.label :description, class: "col-2 col-form-label"%> 
<div class = "col-10">
<%=  f.text_area :description, rows: 5, class: "form-control"%>
</div>
</div>

<div class= "form-group row justify-content-center">
<div class = "container ml-5">
<%= f.submit class: "btn btn-outline-dark btn-sm"%>
</div>
</div>

<%end%>
</div>
<%= link_to 'Return to posts ',posts_path%> 
</div>
</div>

app/views/posts/_post.html.erb
<div class="container">
<% @posts.each do |post| %>
  <div class ="row justify-content-md-center" >
  <div class ="col-8 mt-4">
<div class="card text-center " style="width: 18rem;">
<div class="card-header">By <%= post.user.username  %> 
  <% if post.user %>
              by <%= link_to post.user.username, user_path(post.user) %>
            <% end %>

</div>
  <div class="card-body shadow mb-3 bg-white rounded">
    <h5 class="card-title"><%= link_to post.title, post_path(post), class: "text-success" %></h5>
    <p class="card-text"><%=post.description %></p>
    <%= link_to "View", post_path(post), class: "btn btn-outline-success" %>
    <%= link_to "Edit", edit_post_path(post), class: "btn btn-outline-info" %>
    <%= link_to "Delete", post_path(post), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
</div>
    </div>
    </div>
</div>
<% end%>
</div>

app/views/posts/edit.html.erb
<h1 class= "text-center mt-4">Edit Post</h1>

<%= render 'forms' %>

app/views/posts/index.html.erb
<h1 class= "text-center mt-4">Post Feed</h1>
<div class="apple_pagination">
    <%= will_paginate @posts, :container => false %>
  </div>
<%= render 'post' %>
<div class="apple_pagination">
    <%= will_paginate @posts, :container => false %>
  </div>

app/views/posts/new.html.erb
<h1 class= "text-center mt-4">Make A Post</h1>
<%= render 'forms' %>

app/views/posts/show.html.erb
<h2 class= "text-center mt-4"><%=@post.title%></h2>

    <div class ="row justify-content-md-center" >
    <div class ="col-8 mt-4">
<div class="container">

<div class="card text-center " style="width: 18rem;">
<div class="card-header">By <%= @post.user.username %>  
 <%= link_to gravatar_for(@post.user), user_path(@post.user) %>
</div>
  <div class="card-body shadow mb-3 bg-white rounded">
    <p class="card-text"><%=@post.description %></p>
    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-info" %>
    <%= link_to "Delete", post_path(@post), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
</div>
    </div>
    </div>
</div>
</div>
<div class ="row">

app/views/users/_form.html.erb
<div class  = "container">
<% if @user.errors.any? %>
<h2>The following error or errors occured</h2>
<ul>
<% @user.errors.full_messages.each do |msg|%>
   <li> <%= msg %> </li>
  <% end %>
</ul>
<% end %>
<div class= "row justify-content-center">
<div class = "col-10">
<%= form_with( model: @user, class:"shadow-p-3 mb-5 bg-info rounded", local: true) do |f| %>
  <div class= "form-group row">
<%= f.label :username, class: "col-2 col-form-label"%> 
<div class = "col-10">
<%=  f.text_field :username, class: "form-control", placeholder: "Enter Username" %>
</div>
</div>

<div class= "form-group row">
<%= f.label :email, class: "col-2 col-form-label"%> 
<div class = "col-10">
<%=  f.text_area :email, class: "form-control", placeholder: "Enter Email"%>
</div>
</div>

<div class= "form-group row">
<%= f.label :password, class: "col-2 col-form-label"%> 
<div class = "col-10">
<%=  f.password_field :password, class: "form-control", placeholder: "Enter Password"%>
</div>
</div>

<div class= "form-group row justify-content-center">
<div class = "container ml-5">
   <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
</div>
</div>

<%end%>
</div>
<%= link_to 'Return to posts ',posts_path%> 
</div>
</div>

app/views/users/edit.html.erb
<h1 class= "text-center mt-4">edit profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.posts.count, "Posts") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class= "text-center mt-4">signup</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile </h1>
<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-4">
  <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
</div>


<h3 class="text-center mt-4">Posts</h3>

<%= render 'posts/post' %>